backend/audit/urls.py
from django.urls import path

from audit.fixtures.excel import FORM_SECTIONS
from audit import views

app_name = "audit"


def camel_to_hyphen(raw: str) -> str:
    """Convert camel case to hyphen-delimited."""
    text = f"{raw[0].lower()}{raw[1:]}"
    return "".join(c if c.islower() else f"-{c.lower()}" for c in text)


urlpatterns = [
    path("", views.MySubmissions.as_view(), name="MySubmissions"),
    path("<str:report_id>", views.EditSubmission.as_view(), name="EditSubmission"),
    path(
        "single-audit-report/<str:report_id>",
        views.SingleAuditReportFileHandlerView.as_view(),
        name="SingleAuditReport",
    ),
    path(
        "ready-for-certification/<str:report_id>",
        views.ReadyForCertificationView.as_view(),
        name="ReadyForCertification",
    ),
    path(
        "auditor-certification/<str:report_id>",
        views.AuditorCertificationStep1View.as_view(),
        name="AuditorCertification",
    ),
    path(
        "auditor-certification-confirm/<str:report_id>",
        views.AuditorCertificationStep2View.as_view(),
        name="AuditorCertificationConfirm",
    ),
    path(
        "auditee-certification/<str:report_id>",
        views.AuditeeCertificationStep1View.as_view(),
        name="AuditeeCertification",
    ),
    path(
        "auditee-certification-confirm/<str:report_id>",
        views.AuditeeCertificationStep2View.as_view(),
        name="AuditeeCertificationConfirm",
    ),
    path(
        "certification/<str:report_id>",
        views.CertificationView.as_view(),
        name="Certification",
    ),
    path(
        "submission/<str:report_id>",
        views.SubmissionView.as_view(),
        name="Submission",
    ),
    path(
        "submission-progress/<str:report_id>",
        views.SubmissionProgressView.as_view(),
        name="SubmissionProgress",
    ),
    path(
        "audit-info/<str:report_id>",
        views.AuditInfoFormView.as_view(),
        name="AuditInfoForm",
    ),
    path(
        "upload-report/<str:report_id>",
        views.UploadReportView.as_view(),
        name="UploadReport",
    ),
    path(
        "cross-validation/<str:report_id>",
        views.CrossValidationView.as_view(),
        name="CrossValidation",
    ),
]

for form_section in FORM_SECTIONS:
    urlpatterns.append(
        path(
            f"excel/{camel_to_hyphen(form_section)}/<str:report_id>",
            views.ExcelFileHandlerView.as_view(),
            name=form_section,
            kwargs={"form_section": form_section},
        )
    )

backend/cms/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # home page
    path("", views.Home.as_view(), name="Home"),
    # route for posts
    # path("<slug:slug>/", views.postdetail.as_view(), name="post_detail"),
    path("robots.txt", views.NoRobots, name="no_robots"),
]

backend/config/urls.py
from api import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from rest_framework.renderers import JSONOpenAPIRenderer
from rest_framework.schemas import get_schema_view

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

schema_view = get_schema_view(
    title="Federal Audit Clearinghouse API",
    version=settings.API_VERSION,
    url="http://localhost:8000/api/",
    renderer_classes=[JSONOpenAPIRenderer],
)

urlpatterns = [
    # path("", IndexView.as_view(), name="index"),
    path("api/schema.json", schema_view),
    path("public/api/sac", views.SACViewSet.as_view({"get": "list"}), name="sac-list"),
    path(
        "public/api/sac/<str:report_id>",
        views.SACViewSet.as_view({"get": "retrieve"}),
        name="sac-detail",
    ),
    path(
        "api/sac/eligibility",
        views.EligibilityFormView.as_view(),
        name="api-eligibility",
    ),
    path(
        "api/sac/ueivalidation",
        views.UEIValidationFormView.as_view(),
        name="api-uei-validation",
    ),
    path("api/sac/auditee", views.AuditeeInfoView.as_view(), name="api-auditee-info"),
    path(
        "api/sac/accessandsubmission",
        views.AccessAndSubmissionView.as_view(),
        name="api-accessandsubmission",
    ),
    path(
        "sac/edit/<str:report_id>",
        views.SingleAuditChecklistView.as_view(),
        name="singleauditchecklist",
    ),
    path(
        "sac/edit/<str:report_id>/federal_awards",
        views.SacFederalAwardsView.as_view(),
        name="sacfederalawards",
    ),
    path(
        "submissions",
        views.SubmissionsView.as_view(),
        name="submissions",
    ),
    path(
        "access-list",
        views.AccessListView.as_view(),
        name="access-list",
    ),
    path(
        "schemas/<str:fiscal_year>/<str:schema_type>",
        views.SchemaView.as_view(),
        name="schemas",
    ),
    path(settings.ADMIN_URL, admin.site.urls),
    path("openid/", include("djangooidc.urls")),
    path("report_submission/", include("report_submission.urls")),
    # Due to problematic interactions between the SVG use element and
    # cross-domain rules and serving assets from S3, we need to serve this
    # particular file from Django:
    path(
        "icons/sprite.svg",
        views.Sprite.as_view(),
        name="sprite",
    ),
    path("audit/", include("audit.urls")),
    # Keep last so we can use short urls for content pages like home page etc.
    path("", include("cms.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

backend/report_submission/urls.py
from django.urls import path
from . import views

app_name = "report_submission"

upload_page_ids = [
    "federal-awards",
    "notes-to-sefa",
    "audit-findings",
    "audit-findings-text",
    "CAP",
    "additional-eins",
    "additional-ueis",
    "secondary-auditors",
]

urlpatterns = [
    path("", views.ReportSubmissionRedirectView.as_view(), name="report_submission"),
    path("eligibility/", views.EligibilityFormView.as_view(), name="eligibility"),
    path("auditeeinfo/", views.AuditeeInfoFormView.as_view(), name="auditeeinfo"),
    path(
        "accessandsubmission/",
        views.AccessAndSubmissionFormView.as_view(),
        name="accessandsubmission",
    ),
    path(
        "general-information/<str:report_id>",
        views.GeneralInformationFormView.as_view(),
        name="general_information",
    ),
]

for page_id in upload_page_ids:
    urlpatterns.append(
        path(
            f"{page_id.lower()}/<str:report_id>",
            views.UploadPageView.as_view(),
            name=page_id,
        )
    )

backend/report_submission/models.py
from django.db import models  # noqa: F401

# Create your models here.

backend/report_submission/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import BadRequest, PermissionDenied, ValidationError
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from audit.models import Access, SingleAuditChecklist, LateChangeError, SubmissionEvent

from report_submission.forms import AuditeeInfoForm, GeneralInformationForm

import api.views

from config.settings import STATIC_SITE_URL, STATE_ABBREVS

logger = logging.getLogger(__name__)


class ReportSubmissionRedirectView(View):
    def get(self, request):
        return redirect(reverse("report_submission:eligibility"))


# Step 1
class EligibilityFormView(LoginRequiredMixin, View):
    def get(self, request):
        args = {}
        args["step"] = 1
        return render(request, "report_submission/step-1.html", args)

    # render eligibility form

    # gather/save step 1 info, redirect to step 2
    def post(self, post_request):
        eligibility = api.views.eligibility_check(post_request.user, post_request.POST)
        if eligibility.get("eligible"):
            return redirect(reverse("report_submission:auditeeinfo"))

        return redirect(reverse("report_submission:eligibility"))


# Step 2
class AuditeeInfoFormView(LoginRequiredMixin, View):
    def get(self, request):
        args = {}
        args["step"] = 2
        args["form"] = AuditeeInfoForm()
        return render(request, "report_submission/step-2.html", args)

    # render auditee info form

    # gather/save step 2 info, redirect to step 3
    def post(self, request):
        form = AuditeeInfoForm(request.POST)
        if not form.is_valid():
            context = {
                "form": form,
                "step": 2,
            }
            return render(request, "report_submission/step-2.html", context)

        formatted_post = {
            "csrfmiddlewaretoken": request.POST.get("csrfmiddlewaretoken"),
            "auditee_uei": form.cleaned_data["auditee_uei"],
            "auditee_name": request.POST.get("auditee_name"),
            "auditee_address_line_1": request.POST.get("auditee_address_line_1"),
            "auditee_city": request.POST.get("auditee_city"),
            "auditee_state": request.POST.get("auditee_state"),
            "auditee_zip": request.POST.get("auditee_zip"),
            "auditee_fiscal_period_start": form.cleaned_data[
                "auditee_fiscal_period_start"
            ].strftime("%Y-%m-%d"),
            "auditee_fiscal_period_end": form.cleaned_data[
                "auditee_fiscal_period_end"
            ].strftime("%Y-%m-%d"),
        }

        info_check = api.views.auditee_info_check(request.user, formatted_post)
        if info_check.get("errors"):
            return redirect(reverse("report_submission:auditeeinfo"))

        return redirect(reverse("report_submission:accessandsubmission"))


# Step 3
class AccessAndSubmissionFormView(LoginRequiredMixin, View):
    def get(self, request):
        args = {}
        args["step"] = 3
        return render(request, "report_submission/step-3.html", args)

    # render access-submission form

    # gather/save step 3 info, redirect to step ...4?
    def post(self, post_request):
        result = api.views.access_and_submission_check(
            post_request.user, post_request.POST
        )
        report_id = result.get("report_id")

        if report_id:
            return redirect(f"/report_submission/general-information/{report_id}")
        return redirect(reverse("report_submission:accessandsubmission"))


class GeneralInformationFormView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        report_id = kwargs["report_id"]

        try:
            sac = SingleAuditChecklist.objects.get(report_id=report_id)

            # this should probably be a permission mixin
            accesses = Access.objects.filter(sac=sac, user=request.user)
            if not accesses:
                raise PermissionDenied("You do not have access to this audit.")

            context = {
                "audit_type": sac.audit_type,
                "auditee_fiscal_period_end": sac.auditee_fiscal_period_end,
                "auditee_fiscal_period_start": sac.auditee_fiscal_period_start,
                "audit_period_covered": sac.audit_period_covered,
                "audit_period_other_months": sac.audit_period_other_months,
                "ein": sac.ein,
                "ein_not_an_ssn_attestation": sac.ein_not_an_ssn_attestation,
                "multiple_eins_covered": sac.multiple_eins_covered,
                "auditee_uei": sac.auditee_uei,
                "multiple_ueis_covered": sac.multiple_ueis_covered,
                "auditee_name": sac.auditee_name,
                "auditee_address_line_1": sac.auditee_address_line_1,
                "auditee_city": sac.auditee_city,
                "auditee_state": sac.auditee_state,
                "auditee_zip": sac.auditee_zip,
                "auditee_contact_name": sac.auditee_contact_name,
                "auditee_contact_title": sac.auditee_contact_title,
                "auditee_phone": sac.auditee_phone,
                "auditee_email": sac.auditee_email,
                "user_provided_organization_type": sac.user_provided_organization_type,
                "is_usa_based": sac.is_usa_based,
                "auditor_firm_name": sac.auditor_firm_name,
                "auditor_ein": sac.auditor_ein,
                "auditor_ein_not_an_ssn_attestation": sac.auditor_ein_not_an_ssn_attestation,
                "auditor_country": sac.auditor_country,
                "auditor_international_address": sac.auditor_international_address,
                "auditor_address_line_1": sac.auditor_address_line_1,
                "auditor_city": sac.auditor_city,
                "auditor_state": sac.auditor_state,
                "auditor_zip": sac.auditor_zip,
                "auditor_contact_name": sac.auditor_contact_name,
                "auditor_contact_title": sac.auditor_contact_title,
                "auditor_phone": sac.auditor_phone,
                "auditor_email": sac.auditor_email,
                "secondary_auditors_exist": sac.secondary_auditors_exist,
                "report_id": report_id,
                "state_abbrevs": STATE_ABBREVS,
            }

            return render(request, "report_submission/gen-form.html", context)
        except SingleAuditChecklist.DoesNotExist as err:
            raise PermissionDenied("You do not have access to this audit.") from err

    def post(self, request, *args, **kwargs):
        """
        Handle POST of General Information:
        verify access, validate form data, save, and redirect.
        """
        report_id = kwargs["report_id"]

        try:
            sac = SingleAuditChecklist.objects.get(report_id=report_id)

            accesses = Access.objects.filter(sac=sac, user=request.user)
            if not accesses:
                raise PermissionDenied("You do not have access to this audit.")

            form = GeneralInformationForm(request.POST)

                
            
            if not form.is_valid():
                context = form.cleaned_data | {
                    "errors": form.errors,
                    "report_id": report_id,
                }
                message = ""
                for field, errors in form.errors.items():
                    message = f"{message}\n {field}: {errors}"
                    logger.warning(f"Error {field}: {errors}")
                return render(request, "report_submission/gen-form.html", context)

            form = self._wipe_auditor_address(form)
            general_information = sac.general_information
            general_information.update(form.cleaned_data)
            sac.general_information = general_information
            if general_information.get("audit_type"):
                sac.audit_type = general_information["audit_type"]

            sac.save(
                event_user=request.user,
                event_type=SubmissionEvent.EventType.GENERAL_INFORMATION_UPDATED,
            )

            return redirect(f"/audit/submission-progress/{report_id}")
        except SingleAuditChecklist.DoesNotExist as err:
            raise PermissionDenied("You do not have access to this audit.") from err
        except ValidationError as err:
            message = f"ValidationError for report ID {report_id}: {err.message}"
            print(message)
            raise BadRequest(message)
        except LateChangeError:
            return render(request, "audit/no-late-changes.html")
        except Exception as err:
            message = f"Unexpected error in GeneralInformationFormView post. Report ID {report_id}: {err}"
            logger.warning(message)
            raise BadRequest(message)

    def _wipe_auditor_address(self, form):
        # If non-USA is selected, wipe USA-specific fields
        # Else, wipe the non-USA specific field
        keys_to_wipe = [
            "auditor_address_line_1",
            "auditor_city",
            "auditor_state",
            "auditor_zip",
        ]
        if form.cleaned_data["auditor_country"] == "non-USA":
            for key in keys_to_wipe:
                form.cleaned_data[key] = ""
        else:
            form.cleaned_data["auditor_international_address"] = ""
        return form


class UploadPageView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        report_id = kwargs["report_id"]

        instructions_base_url = STATIC_SITE_URL + "resources/workbooks/"
        workbook_base_url = STATIC_SITE_URL + "assets/workbooks/"

        # Organized by URL name, page specific constants are defined here
        # Data can then be accessed by checking the current URL
        additional_context = {
            "federal-awards": {
                "view_id": "federal-awards",
                "view_name": "Federal awards",

backend/report_submission/templates/report_submission/audit-findings.html
{% extends "base.html" %}
{% load static %}
{% block metatags %}
    <title>{{ post.title }}</title>
    <meta name="description" content="{{ post.meta_description }}" />
    <meta property="og:title" content="{{ post.title }}" />
    <meta property="og:site_name" content="Federal Audit Clearinghouse" />
    <meta property="og:description" content="{{ post.meta_description }}" />
    <meta property="og:type" content="website" />
{% endblock %}
{% block content %}
    <div class="grid-container margin-top-6">
        <div class="grid-row grid-gap">
            {% include "../sidenav.html" %}
            <form class="usa-form usa-form--large" id="audit-findings" method="post">
                {% csrf_token %}
                <fieldset class="usa-fieldset">
                    <legend class="usa-legend usa-legend--large" id="audit-findings">
                        Audit findings
                    </legend>
                    <p>Enter the audit findings for your federal awards using the provided worksheet.</p>
                    <h4 class="usa-process-list__heading">Upload completed worksheet</h4>
                    <p>Save your completed worksheet as an XLSX file and upload it below.</p>
                    <div class="usa-form-group">
                        <input id="file-input-audit-findings-xlsx"
                               class="usa-file-input"
                               type="file"
                               name="file-input-audit-findings-xlsx"
                               aria-describedby="file-input-audit-findings-xlsx"
                               accept=".xlsx"/>
                    </div>
                    <button class="usa-button" id="continue" disabled="disabled">Save and continue to next section</button>
                </fieldset>
            </form>
        </div>
    </div>
    <div class="audit-metadata">
        <div class="grid-container">
            <dl class="grid-row grid-gap">
                <div class="tablet:grid-col-6">
                    <dt>
                        Entity name
                    </dt>
                    <dd>
                        {{ auditee_name | default_if_none:'' }}
                    </dd>
                </div>
                <div class="tablet:grid-col-6">
                    <dt>
                        Report ID
                    </dt>
                    <dd>
                        <!-- Adding the 'json_script' alias allows this variable to be accessed by that name in javascript. -->
                        #{{ report_id | default_if_none:'' }}
                        {{ report_id | json_script:'sac_id' }}
                    </dd>
                </div>
                <div class="tablet:grid-col-6">
                    <dt>
                        UEI
                    </dt>
                    <dd>
                        {{ auditee_uei | default_if_none:'' }}
                    </dd>
                </div>
                <div class="tablet:grid-col-6">
                    <dt>
                        Type of entity
                    </dt>
                    <dd>
                        {{ user_provided_organization_type | default_if_none:'' }}
                    </dd>
                </div>
            </dl>
        </div>
    </div>
    <script src="{% static 'compiled/js/audit-findings.js' %}"></script>
{% endblock content %}

backend/report_submission/templates/report_submission/step-base.html
{% extends "base.html" %}
{% load static %}
{% block metatags %}
    <title>{{ post.title }}</title>
    <meta name="description" content="{{ post.meta_description }}" />
    <meta property="og:title" content="{{ post.title }}" />
    <meta property="og:site_name" content="Federal Audit Clearinghouse" />
    <meta property="og:description" content="{{ post.meta_description }}" />
    <meta property="og:type" content="website" />
{% endblock %}
{% block content %}
    <div class="grid-container">
        <h1>Create new audit</h1>
    </div>
    <div class="grid-container">
        <div class="usa-step-indicator usa-step-indicator--counters-sm"
             role="progressbar"
             aria-label="Form progress"
             aria-valuemin="1"
             aria-valuemax="4"
             aria-valuenow="{{ step }}">
            <ol class="usa-step-indicator__segments">
                <li class="usa-step-indicator__segment {% if step|add:'0' == 1 %} usa-step-indicator__segment--current {% endif %} {% if step|add:'0' > 1 %} usa-step-indicator__segment--complete {% endif %} ">
                    <span class="usa-step-indicator__segment-label">
                        Submission eligibility
                        <span class="usa-sr-only">completed</span>
                    </span>
                </li>
                <li class="usa-step-indicator__segment {% if step|add:'0' == 2 %} usa-step-indicator__segment--current {% endif %} {% if step|add:'0' > 2 %} usa-step-indicator__segment--complete {% endif %} ">
                    <span class="usa-step-indicator__segment-label">Auditee information</span>
                </li>
                <li class="usa-step-indicator__segment {% if step|add:'0' == 3 %} usa-step-indicator__segment--current {% endif %} {% if step|add:'0' > 3 %} usa-step-indicator__segment--complete {% endif %}  ">
                    <span class="usa-step-indicator__segment-label">Audit submission access</span>
                </li>
                <li class="usa-step-indicator__segment">
                    <span class="usa-step-indicator__segment-label">New audit created</span>
                </li>
            </ol>
        </div>
    </div>
    {% block step-content %}{% endblock %}
{% endblock content %}
<script>//const authToken = "aGV5bWF0dDpmYWNzYWMyMDIy"</script>

backend/report_submission/templates/report_submission/upload-page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="grid-container margin-top-6">
        <div class="grid-row">
            {% comment %} {% include "../sidenav.html" %} {% endcomment %}
            <form class="tablet:grid-col-8 tablet:grid-offset-2"
                  id="{{ view_id }}"
                  id_test="upload-page__form"
                  method="post">
                {% csrf_token %}
                <fieldset class="usa-fieldset">
                    <legend class="usa-legend usa-legend--large"
                            id="{{ view_id }}"
                            id_test="upload-page__legend">{{ view_name }}</legend>

                    <p>{{ instructions }}</p>
                    <ul class="margin-top-4">
                        <li>Review the <a class="usa-link" id="instructions-link" href={{instructions_url}} target="_blank">instructions for this workbook.</a></li>
                        <li><a class="usa-link" id="download-template-link" href={{workbook_url}} target="_blank">Download</a> the {{view_name}} workbook template.</li>
                    </ul>

                    {% if no_findings_disclaimer %}
                    <div class="margin-top-4">
                        <h2>If you do not have findings:</h2>
                        <ol>
                            <li>Open the workbook.</li>
                            <li>Enter the auditee UEI.</li>
                            <li>Save and submit the workbook.</li>
                        </ol>
                    </div>
                    {% endif %}

                    <h4 class="usa-process-list__heading margin-top-4">Upload completed worksheet</h4>
                    <p>Save your completed worksheet as an XLSX file and upload it below.</p>
                    <div class="usa-form-group">
                        <input id="file-input-{{ view_id }}-xlsx"
                               class="usa-file-input"
                               id_test="upload-page__file-input"
                               type="file"
                               name="file-input-{{ view_id }}-xlsx"
                               aria-describedby="file-input-{{ view_id }}-xlsx"
                               accept=".xlsx" />
                    </div>
                    {% if already_submitted %}
                        <p class="text-green" id="already-submitted">
                            A file has already been uploaded for this section. A successful reupload will overwrite your previous submission.
                        </p>
                    {% endif %}
                    <div hidden id="info_box" class="grid-row margin-bottom-3 margin-top-3"></div>
                    <button class="usa-button margin-bottom-8" id="continue" disabled="disabled">Return to Report Home</button>
                    <a class="usa-button usa-button--unstyled margin-left-2" href="{% url 'audit:SubmissionProgress' report_id %}"
                    aria-controls="upload-cancel">Cancel</a>
                </fieldset>
            </form>
        </div>
    </div>
    {% include "audit-metadata.html" %}
    <!-- Pass variables to JS as given alias -->
    {{ report_id | json_script:'sac_id' }}
    {{ view_id | json_script:'view_id' }}
    <script src="{% static 'compiled/js/upload-page.js' %}"></script>
{% endblock content %}