backend/audit/urls.py
from django.urls import path

from audit.fixtures.excel import FORM_SECTIONS
from audit import views

app_name = "audit"


def camel_to_hyphen(raw: str) -> str:
    """Convert camel case to hyphen-delimited."""
    text = f"{raw[0].lower()}{raw[1:]}"
    return "".join(c if c.islower() else f"-{c.lower()}" for c in text)


urlpatterns = [
    path("", views.MySubmissions.as_view(), name="MySubmissions"),
    path("<str:report_id>", views.EditSubmission.as_view(), name="EditSubmission"),
    path(
        "single-audit-report/<str:report_id>",
        views.SingleAuditReportFileHandlerView.as_view(),
        name="SingleAuditReport",
    ),
    path(
        "ready-for-certification/<str:report_id>",
        views.ReadyForCertificationView.as_view(),
        name="ReadyForCertification",
    ),
    path(
        "auditor-certification/<str:report_id>",
        views.AuditorCertificationStep1View.as_view(),
        name="AuditorCertification",
    ),
    path(
        "auditor-certification-confirm/<str:report_id>",
        views.AuditorCertificationStep2View.as_view(),
        name="AuditorCertificationConfirm",
    ),
    path(
        "auditee-certification/<str:report_id>",
        views.AuditeeCertificationStep1View.as_view(),
        name="AuditeeCertification",
    ),
    path(
        "auditee-certification-confirm/<str:report_id>",
        views.AuditeeCertificationStep2View.as_view(),
        name="AuditeeCertificationConfirm",
    ),
    path(
        "certification/<str:report_id>",
        views.CertificationView.as_view(),
        name="Certification",
    ),
    path(
        "submission/<str:report_id>",
        views.SubmissionView.as_view(),
        name="Submission",
    ),
    path(
        "submission-progress/<str:report_id>",
        views.SubmissionProgressView.as_view(),
        name="SubmissionProgress",
    ),
    path(
        "audit-info/<str:report_id>",
        views.AuditInfoFormView.as_view(),
        name="AuditInfoForm",
    ),
    path(
        "upload-report/<str:report_id>",
        views.UploadReportView.as_view(),
        name="UploadReport",
    ),
    path(
        "cross-validation/<str:report_id>",
        views.CrossValidationView.as_view(),
        name="CrossValidation",
    ),
]

for form_section in FORM_SECTIONS:
    urlpatterns.append(
        path(
            f"excel/{camel_to_hyphen(form_section)}/<str:report_id>",
            views.ExcelFileHandlerView.as_view(),
            name=form_section,
            kwargs={"form_section": form_section},
        )
    )

backend/cms/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # home page
    path("", views.Home.as_view(), name="Home"),
    # route for posts
    # path("<slug:slug>/", views.postdetail.as_view(), name="post_detail"),
    path("robots.txt", views.NoRobots, name="no_robots"),
]

backend/config/urls.py
from api import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from rest_framework.renderers import JSONOpenAPIRenderer
from rest_framework.schemas import get_schema_view

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

schema_view = get_schema_view(
    title="Federal Audit Clearinghouse API",
    version=settings.API_VERSION,
    url="http://localhost:8000/api/",
    renderer_classes=[JSONOpenAPIRenderer],
)

urlpatterns = [
    # path("", IndexView.as_view(), name="index"),
    path("api/schema.json", schema_view),
    path("public/api/sac", views.SACViewSet.as_view({"get": "list"}), name="sac-list"),
    path(
        "public/api/sac/<str:report_id>",
        views.SACViewSet.as_view({"get": "retrieve"}),
        name="sac-detail",
    ),
    path(
        "api/sac/eligibility",
        views.EligibilityFormView.as_view(),
        name="api-eligibility",
    ),
    path(
        "api/sac/ueivalidation",
        views.UEIValidationFormView.as_view(),
        name="api-uei-validation",
    ),
    path("api/sac/auditee", views.AuditeeInfoView.as_view(), name="api-auditee-info"),
    path(
        "api/sac/accessandsubmission",
        views.AccessAndSubmissionView.as_view(),
        name="api-accessandsubmission",
    ),
    path(
        "sac/edit/<str:report_id>",
        views.SingleAuditChecklistView.as_view(),
        name="singleauditchecklist",
    ),
    path(
        "sac/edit/<str:report_id>/federal_awards",
        views.SacFederalAwardsView.as_view(),
        name="sacfederalawards",
    ),
    path(
        "submissions",
        views.SubmissionsView.as_view(),
        name="submissions",
    ),
    path(
        "access-list",
        views.AccessListView.as_view(),
        name="access-list",
    ),
    path(
        "schemas/<str:fiscal_year>/<str:schema_type>",
        views.SchemaView.as_view(),
        name="schemas",
    ),
    path(settings.ADMIN_URL, admin.site.urls),
    path("openid/", include("djangooidc.urls")),
    path("report_submission/", include("report_submission.urls")),
    # Due to problematic interactions between the SVG use element and
    # cross-domain rules and serving assets from S3, we need to serve this
    # particular file from Django:
    path(
        "icons/sprite.svg",
        views.Sprite.as_view(),
        name="sprite",
    ),
    path("audit/", include("audit.urls")),
    # Keep last so we can use short urls for content pages like home page etc.
    path("", include("cms.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

backend/audit/views.py
import logging

from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.db.models import F
from django.core.exceptions import BadRequest, PermissionDenied, ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.decorators import method_decorator
from django.http import JsonResponse

from config.settings import (
    AGENCY_NAMES,
    GAAP_RESULTS,
    SP_FRAMEWORK_BASIS,
    SP_FRAMEWORK_OPINIONS,
)
from audit.fixtures.excel import FORM_SECTIONS, UNKNOWN_WORKBOOK

from audit.excel import (
    extract_additional_ueis,
    extract_additional_eins,
    extract_federal_awards,
    extract_corrective_action_plan,
    extract_findings_text,
    extract_findings_uniform_guidance,
    extract_secondary_auditors,
    extract_notes_to_sefa,
)
from audit.forms import (
    AuditInfoForm,
    AuditorCertificationStep1Form,
    AuditorCertificationStep2Form,
    AuditeeCertificationStep1Form,
    AuditeeCertificationStep2Form,
)
from audit.mixins import (
    CertifyingAuditeeRequiredMixin,
    CertifyingAuditorRequiredMixin,
    SingleAuditChecklistAccessRequiredMixin,
)
from audit.models import (
    Access,
    ExcelFile,
    LateChangeError,
    SingleAuditChecklist,
    SingleAuditReportFile,
    SubmissionEvent,
)
from audit.utils import ExcelExtractionError
from audit.validators import (
    validate_additional_ueis_json,
    validate_additional_eins_json,
    validate_audit_information_json,
    validate_auditee_certification_json,
    validate_auditor_certification_json,
    validate_corrective_action_plan_json,
    validate_federal_award_json,
    validate_findings_text_json,
    validate_findings_uniform_guidance_json,
    validate_notes_to_sefa_json,
    validate_secondary_auditors_json,
)
from audit.viewlib import (  # noqa
    SubmissionProgressView,
    UploadReportView,
    submission_progress_check,
)


logging.basicConfig(
    format="%(asctime)s %(levelname)-8s %(module)s:%(lineno)d %(message)s"
)
logger = logging.getLogger(__name__)


# 2023-08-22 DO NOT ADD ANY FURTHER CODE TO THIS FILE; ADD IT IN viewlib AS WITH UploadReportView


class MySubmissions(LoginRequiredMixin, generic.View):
    redirect_field_name = "Home"

    def get(self, request, *args, **kwargs):
        template_name = "audit/my_submissions.html"
        new_link = "report_submission"
        edit_link = "audit:EditSubmission"

        submissions = MySubmissions.fetch_my_submissions(request.user)

        data = {"completed_audits": [], "in_progress_audits": []}
        for audit in submissions:
            audit["submission_status"] = (
                audit["submission_status"].replace("_", " ").title()
            )  # auditee_certified --> Auditee Certified
            if audit["submission_status"] == "Submitted":
                data["completed_audits"].append(audit)
            else:
                data["in_progress_audits"].append(audit)

        context = {
            "data": data,
            "new_link": new_link,
            "edit_link": edit_link,
        }
        return render(request, template_name, context)

    @classmethod
    def fetch_my_submissions(cls, user):
        """
        Get all submissions the user is associated with via Access objects.
        """
        accesses = Access.objects.filter(user=user)
        sac_ids = [access.sac.id for access in accesses]
        data = SingleAuditChecklist.objects.filter(id__in=sac_ids).values(
            "report_id",
            "submission_status",
            auditee_uei=F("general_information__auditee_uei"),
            auditee_name=F("general_information__auditee_name"),
            fiscal_year_end_date=F("general_information__auditee_fiscal_period_end"),
        )
        return data


class EditSubmission(LoginRequiredMixin, generic.View):
    redirect_field_name = "Home"

    def get(self, request, *args, **kwargs):
        report_id = kwargs["report_id"]
        return redirect(reverse("singleauditchecklist", args=[report_id]))


class ExcelFileHandlerView(SingleAuditChecklistAccessRequiredMixin, generic.View):
    FORM_SECTION_HANDLERS = {
        FORM_SECTIONS.FEDERAL_AWARDS_EXPENDED: {
            "extractor": extract_federal_awards,
            "field_name": "federal_awards",
            "validator": validate_federal_award_json,
        },
        FORM_SECTIONS.CORRECTIVE_ACTION_PLAN: {
            "extractor": extract_corrective_action_plan,
            "field_name": "corrective_action_plan",
            "validator": validate_corrective_action_plan_json,
        },
        FORM_SECTIONS.FINDINGS_UNIFORM_GUIDANCE: {
            "extractor": extract_findings_uniform_guidance,
            "field_name": "findings_uniform_guidance",
            "validator": validate_findings_uniform_guidance_json,
        },
        FORM_SECTIONS.FINDINGS_TEXT: {
            "extractor": extract_findings_text,
            "field_name": "findings_text",
            "validator": validate_findings_text_json,
        },
        FORM_SECTIONS.ADDITIONAL_UEIS: {
            "extractor": extract_additional_ueis,
            "field_name": "additional_ueis",
            "validator": validate_additional_ueis_json,
        },
        FORM_SECTIONS.ADDITIONAL_EINS: {
            "extractor": extract_additional_eins,
            "field_name": "additional_eins",
            "validator": validate_additional_eins_json,
        },
        FORM_SECTIONS.SECONDARY_AUDITORS: {
            "extractor": extract_secondary_auditors,
            "field_name": "secondary_auditors",
            "validator": validate_secondary_auditors_json,
        },
        FORM_SECTIONS.NOTES_TO_SEFA: {
            "extractor": extract_notes_to_sefa,
            "field_name": "notes_to_sefa",
            "validator": validate_notes_to_sefa_json,
        },
    }

    def _create_excel_file(self, file, sac_id, form_section):
        excel_file = ExcelFile(
            **{
                "file": file,
                "filename": "temp",
                "sac_id": sac_id,
                "form_section": form_section,
            }
        )
        excel_file.full_clean()
        return excel_file

    def _event_type(self, form_section):
        return {
            FORM_SECTIONS.ADDITIONAL_EINS: SubmissionEvent.EventType.ADDITIONAL_EINS_UPDATED,
            FORM_SECTIONS.ADDITIONAL_UEIS: SubmissionEvent.EventType.ADDITIONAL_UEIS_UPDATED,
            FORM_SECTIONS.CORRECTIVE_ACTION_PLAN: SubmissionEvent.EventType.CORRECTIVE_ACTION_PLAN_UPDATED,
            FORM_SECTIONS.FEDERAL_AWARDS_EXPENDED: SubmissionEvent.EventType.FEDERAL_AWARDS_UPDATED,
            FORM_SECTIONS.FINDINGS_TEXT: SubmissionEvent.EventType.FEDERAL_AWARDS_AUDIT_FINDINGS_TEXT_UPDATED,
            FORM_SECTIONS.FINDINGS_UNIFORM_GUIDANCE: SubmissionEvent.EventType.FINDINGS_UNIFORM_GUIDANCE_UPDATED,
            FORM_SECTIONS.NOTES_TO_SEFA: SubmissionEvent.EventType.NOTES_TO_SEFA_UPDATED,
            FORM_SECTIONS.SECONDARY_AUDITORS: SubmissionEvent.EventType.SECONDARY_AUDITORS_UPDATED,
        }[form_section]

    def _extract_and_validate_data(self, form_section, excel_file):
        handler_info = self.FORM_SECTION_HANDLERS.get(form_section)
        if handler_info is None:
            logger.warning("No form section found with name %s", form_section)
            raise BadRequest()
        audit_data = handler_info["extractor"](excel_file.file)
        validator = handler_info.get("validator")
        if validator is not None and callable(validator):
            validator(audit_data)
        return audit_data

    def _save_audit_data(self, sac, form_section, audit_data):
        handler_info = self.FORM_SECTION_HANDLERS.get(form_section)
        if handler_info is not None:
            setattr(sac, handler_info["field_name"], audit_data)
            sac.save()

    # this is marked as csrf_exempt to enable by-hand testing via tools like Postman. Should be removed when the frontend form is implemented!
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(ExcelFileHandlerView, self).dispatch(*args, **kwargs)

    def post(self, request, *_args, **kwargs):
        """
        Handle Excel file upload:
        validate Excel, validate data, verify SAC exists, redirect.
        """
        try:
            report_id = kwargs["report_id"]

            form_section = kwargs["form_section"]

            sac = SingleAuditChecklist.objects.get(report_id=report_id)

            file = request.FILES["FILES"]

            excel_file = self._create_excel_file(file, sac.id, form_section)

            excel_file.save(
                event_user=request.user, event_type=self._event_type(form_section)
            )

            audit_data = self._extract_and_validate_data(form_section, excel_file)

            self._save_audit_data(sac, form_section, audit_data)

            return redirect("/")

        except SingleAuditChecklist.DoesNotExist as err:
            logger.warning("no SingleAuditChecklist found with report ID %s", report_id)
            raise PermissionDenied() from err
        except ValidationError as err:
            # The good error, where bad rows/columns are sent back in the request.
            # These come back as tuples:
            # [(col1, row1, field1, link1, help-text1), (col2, row2, ...), ...]
            logger.warning("%s Excel upload failed validation: %s", form_section, err)
            return JsonResponse({"errors": list(err), "type": "error_row"}, status=400)
        except MultiValueDictKeyError as err:
            logger.warning("No file found in request")
            raise BadRequest() from err
        except KeyError as err:
            logger.warning("Field error. Field: %s", err)

backend/audit/templates/audit/submission_checklist/created-by.html
{% comment %} 
    <p> for created by time and name.
    If no name is available, uses email.

    Examples:
    Completed (formatted time) by (name or email).
    Completed MMM DD, YYYY at 12:00 AM UST by Joe Smith.

    Variables: 
        time (string)
        name (object)
{% endcomment %}
<p class="text-base margin-0">
    {% if name %}
        Completed {{ time|date:"N j, Y g:i A T" }} by
        {% if name.first_name == '' %}
            {{ name.email }}.
        {% else %}
            {{ name.first_name }} {{ name.last_name }}.
        {% endif %}
    {% elif time %}
        Completed {{ time }}.
    {% endif %}
</p>

backend/audit/templates/audit/submission_checklist/icon-list-icon.html
{% comment %} 
    <div> for icon list icon.
    If completed, use a success-darker (dark green) check.
    If incomplete, an empty checkbox.
    Else if inactive, an empty space.

    Variables: 
        completed (bool)
        display (str)
{% endcomment %}
{% load sprite_helper %}
{% if completed %}
  <div class="usa-icon-list__icon text-success-darker">
    <svg class="usa-icon margin-right-3" aria-hidden="true" role="img">
      {% uswds_sprite "check_circle" %}
    </svg>
  </div>
{% elif display == 'incomplete' %}
  <div class="usa-icon-list__icon ">
    <svg class="usa-icon margin-right-3" aria-hidden="true" role="img">
      {% comment %} {% uswds_sprite "radio_button_unchecked" %} {% endcomment %}
    </svg>
</div>
{% else %}
  <div class="usa-icon-list__icon text-disabled-dark">
    <svg class="usa-icon margin-right-3" aria-hidden="true" role="img">
      {% comment %} {% uswds_sprite "radio_button_unchecked" %} {% endcomment %}
    </svg>
  </div>
{% endif %}

backend/audit/templates/audit/submission_checklist/submission-checklist.html
{% extends "base.html" %}
{% load static %}
{% load sprite_helper %}
{% load submission_progress_tags %}
{% block content %}
    <div class="grid-row">
        <div class="grid-container margin-top-6 margin-bottom-6">
            
            {% include './title.html'  with auditee_name=auditee_name %}
            
            <div id="submission-checklist-content">
                <ul class="usa-icon-list usa-icon-list--size-sm tablet:grid-col-11 font-sans-md">

                  {% section_block report_id general_information %}
                  {% section_block report_id audit_information %}
                  {% section_block report_id single_audit_report %}
                  {% section_block report_id federal_awards %}
                  {% section_block report_id notes_to_sefa %}
                  {% section_block report_id findings_uniform_guidance %}
                  {% section_block report_id findings_text %}
                  {% section_block report_id corrective_action_plan %}
                  {% section_block report_id additional_ueis %}
                  {% section_block report_id secondary_auditors %}
                  {% section_block report_id additional_eins %}
                    
                  {% comment %} Key information (certification steps) {% endcomment %}
                    <div class="padding-bottom-3 padding-top-105" id="submission-checklist-summary">
                        <div class="usa-summary-box font-sans-md"
                             role="region"
                             aria-labelledby="summary-box-key-information">
                            <div class="usa-summary-box__body">
                                <div class="usa-summary-box__text">
                                    <span class="text-bold margin-left-1">Key information</span>
                                    <ul class="margin-top-0">
                                        <li>The following steps will remain locked until you have completed all prior steps.</li>
                                        <li class="text-bold">You cannot re-upload documents after certification by either party.</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    {% comment %} Pre-submission validation {% endcomment %}
                    <li class="usa-icon-list__item padding-bottom-105" id="SF-SAC-completed">
                        {% if pre_submission_validation.completed %}
                            {% include './icon-list-icon.html' with completed=pre_submission_validation.completed %}
                            <div class="text-success-darker">
                                <p class="text-bold text-underline margin-0">Pre-submission validation (Complete)</p>
                                <p class="margin-0">Before submitting your audit, use our validation tool to check your workbooks for errors.</p>
                            </div>
                        {% else %}
                            {% include './icon-list-icon.html' with completed=pre_submission_validation.completed %}
                            <div>
                                <p class="text-bold margin-0">
                                    <a class="usa-link"
                                       href="{% url 'audit:CrossValidation' report_id %}">Pre-submission validation</a>
                                </p>
                                <p class="margin-0">Before submitting your audit, use our validation tool to check your workbooks for errors.</p>
                            </div>
                        {% endif %}
                    </li>
                    
                    {% comment %} Auditor Certification {% endcomment %}
                    <li class="usa-icon-list__item padding-bottom-105"
                        id="auditor-certification-completed">
                        {% if certification.auditor_certified %}
                            {% include './icon-list-icon.html' with completed=certification.auditor_certified %}
                            <div class="text-success-darker">
                                <p class="text-bold text-underline margin-0">Auditor Certification (Complete)</p>
                                <p class="margin-0">
                                    Your certifying auditor must attest and sign the single audit package before submission. In order to unlock this step, you must complete and upload all required workbooks from the previous steps, as well as the single audit report PDF.
                                </p>
                            </div>
                        {% elif certification.auditor_enabled %}
                            {% include './icon-list-icon.html' with completed=certification.auditor_certified %}
                            <div>
                                <p class="text-bold margin-0">
                                    <a class="usa-link"
                                       href="{% url 'audit:AuditorCertification' report_id %}">Auditor Certification</a>
                                </p>
                                <p class="margin-0">
                                    Your certifying auditor must attest and sign the single audit package before submission. In order to unlock this step, you must complete and upload all required workbooks from the previous steps, as well as the single audit report PDF.
                                </p>
                            </div>
                        {% else %}
                            {% include './icon-list-icon.html' with completed=certification.auditor_certified %}
                            <div>
                                <p class="text-bold margin-0">Auditor Certification</p>
                                <p class="margin-0">
                                    Your certifying auditor must attest and sign the single audit package before submission. In order to unlock this step, you must complete and upload all required workbooks from the previous steps, as well as the single audit report PDF.
                                </p>
                            </div>
                        {% endif %}
                    </li>
                    
                    {% comment %} Auditee Certification {% endcomment %}
                    <li class="usa-icon-list__item padding-bottom-3"
                        id="auditee-certification-completed">
                        {% if certification.auditee_certified %}
                            {% include './icon-list-icon.html' with completed=certification.auditee_certified %}
                            <div class="text-success-darker">
                                <p class="text-bold text-underline margin-0">Auditee Certification (Complete)</p>
                                <p class="margin-0">
                                    Your certifying auditee must attest and sign the single audit package before submission. In order to unlock this step, you must complete and upload all required workbooks from the previous steps, as well as the single audit report PDF.
                                </p>
                            </div>
                        {% elif certification.auditee_enabled %}
                            {% include './icon-list-icon.html' with completed=certification.auditee_certified %}
                            <div>
                                <p class="text-bold margin-0">
                                    <a class="usa-link"
                                       href="{% url 'audit:AuditeeCertification' report_id %}">Auditee Certification</a>
                                </p>
                                <p class="margin-0">
                                    Your certifying auditee must attest and sign the single audit package before submission. In order to unlock this step, you must complete and upload all required workbooks from the previous steps, as well as the single audit report PDF.
                                </p>
                            </div>
                        {% else %}
                            {% include './icon-list-icon.html' with completed=certification.auditee_certified %}
                            <div>
                                <p class="text-bold margin-0">Auditee Certification</p>
                                <p class="margin-0">
                                    Your certifying auditee must attest and sign the single audit package before submission. In order to unlock this step, you must complete and upload all required workbooks from the previous steps, as well as the single audit report PDF.
                                </p>
                            </div>
                        {% endif %}
                    </li>
                    
                    {% comment %} Submit to the FAC for processing {% endcomment %}
                    {% if submission.enabled %}
                    <div class="padding-bottom-3" id="submit-audit">
                        <div class="usa-summary-box font-sans-md bg-success-lighter"
                             role="region"
                             aria-labelledby="summary-box-key-information">
                            <div class="usa-summary-box__body">
                                <div class="usa-summary-box__text">
                                    <p class="text-bold margin-0">
                                        <a class="usa-link" href="{% url 'audit:Submission' report_id %}">Submit to the FAC for processing</a>
                                    </p>
                                    <p class="margin-0">
                                        This is the last step and must be completed by the <span class="text-underline">certifying auditee</span>. <strong>Once the audit has been submitted, it cannot be undone.</strong>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="padding-bottom-3" id="submit-audit">
                        <div class="usa-summary-box font-sans-md bg-success-lighter"
                             role="region"
                             aria-labelledby="summary-box-key-information">
                            <div class="usa-summary-box__body">
                                <div class="usa-summary-box__text">
                                    <p class="text-bold margin-0">
                                        Submit to the FAC for processing
                                    </p>
                                    <p class="margin-0">
                                        This is the last step and must be completed by the <span class="text-underline">certifying auditee</span>. <strong>Once the audit has been submitted, it cannot be undone.</strong>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% include "audit-metadata.html" %}
{% endblock content %}

backend/audit/templates/audit/submission_checklist/title.html
<div class="grid-row" id="submission-checklist-title">
    <div class="padding-bottom-3" id="submission-checklist-summary">
        <h1 class="border-base-light font-sans-2xl">Submission Checklist: {{ auditee_name | default_if_none:'' }}</h1>
        <div class="usa-summary-box font-sans-md"
             role="region"
             aria-labelledby="summary-box-key-information">
            <div class="usa-summary-box__body">
                <div class="usa-summary-box__text">
                    <span class="text-bold margin-left-1">Key information</span>
                    <ul class="margin-top-0">
                        <li>Use this checklist to track your progress towards completing a single audit submission.</li>
                        <li>Revised files may be re-uploaded at any point before certification.</li>
                        <li>
                            Access this page from your logged-in <a href="{% url 'audit:MySubmissions' %}">home screen.</a>
                        </li>
                        <li class="text-bold">Workbook 1: Federal Awards must be uploaded before any other workbooks can be uploaded.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% comment %}
    Manage Report Access button - uncomment post-MVP. 
    <div class="tablet:grid-col-auto">
        <button class="usa-button usa-button--outline grid-row margin-top-3">
            <svg class="usa-icon usa-icon--size-3 margin-right-1" aria-hidden="true" focusable="false" role="img">
                {% uswds_sprite "person_add" %}
            </svg>
            <span class="padding-top-05">Manage report access</span>
        </button>
    </div> 
    {% endcomment %}
</div>